version: '3.8'

services:
  release-rc-bot:
    build: .
    ports:
      - "5000:5000"
    environment:
      # Slack credentials (set these in .env file)
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_APP_TOKEN=${SLACK_APP_TOKEN}
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
      
      # Bot configuration
      - REMINDER_INTERVAL_HOURS=2
      - RELEASE_CHANNEL=#release-rc
      - TIMEZONE=America/Los_Angeles
      
      # Server settings
      - HOST=0.0.0.0
      - PORT=5000
      - DEBUG=false
      
      # External integrations
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - SLACK_BOT_URL=${SLACK_BOT_URL}
      - SLACK_BOT_API_KEY=${SLACK_BOT_API_KEY}
      
      # Deployment
      - DEPLOYMENT_MODE=production
      - LOG_LEVEL=INFO
    
    volumes:
      # For development - mount source code
      - .:/app
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for production persistence
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    profiles: ["with-redis"]

volumes:
  redis_data: 