# =============================================================================
# Automated RC Release Workflow - Configuration Template
# =============================================================================
# Copy this file to settings.yaml and customize for your organization

# Slack Configuration
slack:
  bot_token: "xoxb-test-token-123"
  signing_secret: "test-signing-secret"
  app_token: "xapp-test-app-token-123"  # For Socket Mode
  default_channels:
    - "#releases"
    - "#general"
  
# GitHub Configuration  
github:
  token: "ghp_test-token-123"
  repo: "test-org/test-repo"  # Format: owner/repo
  api_url: "https://api.github.com"  # For GitHub Enterprise: https://your-enterprise.github.com/api/v3
  
# AI Configuration (multiple providers supported)
ai:
  provider: "openai"  # openai, azure, anthropic
  openai:
    api_key: "test-openai-key-123"
    model: "gpt-4-1106-preview"
    api_base: "https://api.openai.com/v1"
  azure:
    endpoint: "https://test.openai.azure.com"
    api_key: "test-azure-key-123"
    api_version: "2023-12-01-preview"
    deployment: "test-deployment"
  anthropic:
    api_key: "test-anthropic-key-123"
    model: "claude-3-sonnet-20240229"

# LLM Gateway Configuration
llm:
  gateway_url: "https://test-llm-gateway.example.com"
  timeout: 30
  max_retries: 3

# Organization-specific Settings
organization:
  name: "Test Company"
  default_service: "test-service"
  timezone: "UTC"
  regions:
    - "EUS"  # East US
    - "SCUS" # South Central US
    - "WUS"  # West US
  
  # International and tenant labels that should be included in section 9
  international_labels:
    - "international"
    - "i18n"
    - "localization"
    - "locale"
    - "tenant"
    - "multi-tenant"
    - "internationalization"

# Application Settings
app:
  environment: "development"
  log_level: "INFO"
  deployment_mode: "socket"  # socket, http
  port: 3000
  output_dir: "test_output"

# Modal Field Configuration
modal:
  fields:
    production_version:
      required: true
      validation: "^v?\\d+\\.\\d+\\.\\d+$"  # Semantic versioning
      placeholder: "e.g., v1.2.3"
    new_version:
      required: true
      validation: "^v?\\d+\\.\\d+\\.\\d+$"
      placeholder: "e.g., v1.3.0"
    service_name:
      required: true
      validation: "^[a-z][a-z0-9-]*[a-z0-9]$"  # kebab-case
      placeholder: "e.g., cer-cart"
    release_type:
      required: true
      options:
        - "standard"
        - "hotfix" 
        - "ebf"  # Emergency Bug Fix
      default: "standard"
    rc_name:
      required: true
      placeholder: "Who's running the release"
    rc_manager:
      required: true
      placeholder: "Who to escalate to"
    day1_date:
      required: true
      type: "date"
      description: "CRQ Day 1 (prep/setup)"
    day2_date:
      required: true
      type: "date"
      description: "CRQ Day 2 (actual release)"

# CRQ Template Configuration
crq:
  template_fields:
    # These map to your CRQ template structure
    summary_format: "{service_name} Application Code deployment for {platform} ({regions}) - {day_type}"
    
    # Standard questions for Description section
    description_questions:
      - "What is the criticality of change or why is this change required?"
      - "How have we validated this change in the lower environment?"
      - "What is the blast radius of this change?"
      - "Describe how testing has reduced risk for the deployment?"
      - "What happens if we encounter an issue during release?"
      - "What controls do we have to minimize the impact to our customers?"
      - "What monitoring is in place to determine the errors?"
    
    # Required fields for Implementation Plan
    implementation_fields:
      - "Application Name"
      - "Namespace"
      - "Assembly"
      - "Service name"
      - "Platform"
      - "Artifact Version"
      - "Forward Artifact Version"
      - "Rollback Artifact Version"
      - "Confluence link"
    
    # Dashboard links for Validation Plan
    validation_dashboards:
      - "P0 Dashboard – Grafana Link"
      - "L1 Dashboard – Grafana Link"
      - "Services dashboard – Grafana Link"
      - "WCNP - CPU - Memory – Link"
      - "Istio/ SM: Link"
    
    # Backout plan requirements
    backout_fields:
      - "Application Name"
      - "Namespace"
      - "Assembly"
      - "Service name"
      - "Platform"
      - "Artifact Version (Previous Version for rollback)"
      - "Confluence link"

# Template Configuration
templates:
  base_path: "templates"
  release_notes: "release_notes.j2"
  crq_template: "crq_template.j2"
  slack_message: "slack_message.j2"
  
  # Custom template overrides
  custom_path: "${CUSTOM_TEMPLATE_DIR:}"
  
  # Output formats
  formats:
    confluence: true
    markdown: true
    html: false
    plain_text: false

# Security & Access Control
security:
  allowed_users: []  # Empty means all workspace members
  allowed_channels: []  # Empty means all channels
  require_manager_approval: false
  
# Monitoring & Alerting
monitoring:
  webhook_url: "${MONITORING_WEBHOOK_URL:}"
  sentry_dsn: "${SENTRY_DSN:}"
  enable_metrics: true

# Integration Settings
integrations:
  jira:
    enabled: false
    url: "${JIRA_URL:}"
    username: "${JIRA_USERNAME:}"
    api_token: "${JIRA_API_TOKEN:}"
  
  servicenow:
    enabled: false
    instance: "${SERVICENOW_INSTANCE:}"
    username: "${SERVICENOW_USERNAME:}"
    password: "${SERVICENOW_PASSWORD:}"

# Dashboard Configuration
dashboard:
  confluence_dashboard_url: "https://confluence.test.com/display/SERVICE/Dashboards"
  p0_dashboard_url: "https://grafana.test.com/d/service-p0"
  l1_dashboard_url: "https://grafana.test.com/d/service-l1"
  services_dashboard_url: "https://grafana.test.com/d/services"
  wcnp_dashboard_url: "https://grafana.test.com/d/wcnp"
  istio_dashboard_url: "https://grafana.test.com/d/istio"

# External Template Configuration
external_template:
  enabled: false  # Disabled for testing to avoid download errors
  template_url: "https://sharepoint.test.com/CRQ_Template.docx"
  fallback_to_builtin: true
  cache_duration: 3600 