# =============================================================================
# Automated RC Release Workflow - Configuration
# =============================================================================

# Slack Configuration (minimal for testing - UPDATE WITH REAL TOKENS WHEN AVAILABLE)
slack:
  bot_token: "xoxb-000000000000-000000000000-placeholder-for-testing"  # Replace with real token
  signing_secret: "placeholder-signing-secret"
  app_token: ""  # Optional for Socket Mode
  default_channels:
    - "#releases"
  
# GitHub Configuration  
github:
  token: "xoxb-000000000000-000000000000-placeholder-for-testing"  # Your working token
  repo: "ArnoldoM23/PerfCopilot"
  api_url: "https://api.github.com"
  
# AI Configuration
ai:
  provider: "openai"
  openai:
    api_key: "placeholder"  # Set your OpenAI key here or use env var
    model: "gpt-4-1106-preview"
    max_tokens: 1000

# Organization-specific Settings
organization:
  name: "ArnoldoM23"
  default_service: "ce-cartxo"
  timezone: "UTC"
  regions:
    - "EUS"
    - "SCUS" 
    - "WUS"
  platform: "Glass"
  
  # International and tenant labels that should be included in section 9
  international_labels:
    - "international"
    - "i18n"
    - "localization"
    - "locale"
    - "tenant"
    - "multi-tenant"
    - "internationalization"

# Application Settings
app:
  environment: "development"
  log_level: "INFO"
  deployment_mode: "socket"
  port: 3000
  output_dir: "output"

# CRQ Template Configuration
crq:
  template_fields:
    summary_format: "{service_name} Application Code deployment for {platform} ({regions}) - {day_type}"
    description_questions:
      - "What is the criticality of change or why is this change required?"
      - "How have we validated this change in the lower environment?"
      - "What is the blast radius of this change?"
      - "Describe how testing has reduced risk for the deployment?"
      - "What happens if we encounter an issue during release?"
      - "What controls do we have to minimize the impact to our customers?"
      - "What monitoring is in place to determine the errors?"
    implementation_fields:
      - "Application Name"
      - "Namespace"
      - "Assembly"
      - "Service name"
      - "Platform"
      - "Artifact Version"
      - "Forward Artifact Version"
      - "Rollback Artifact Version"
      - "Confluence link"
    validation_dashboards:
      - "P0 Dashboard – Grafana Link"
      - "L1 Dashboard – Grafana Link"
      - "Services dashboard – Grafana Link"
      - "WCNP - CPU - Memory – Link"
      - "Istio/ SM: Link"
    backout_fields:
      - "Application Name"
      - "Namespace"
      - "Assembly"
      - "Service name"
      - "Platform"
      - "Artifact Version (Previous Version for rollback)"
      - "Confluence link"

# Template Configuration
templates:
  base_path: "src/templates"
  release_notes: "release_notes.j2"
  crq_template: "crq_template.j2"
  slack_message: "slack_message.j2"
  custom_path: ""
  formats:
    confluence: true
    markdown: true
    html: false
    plain_text: false

# Security & Access Control
security:
  allowed_users: []
  allowed_channels: []
  require_manager_approval: false
  
# Monitoring & Alerting
monitoring:
  webhook_url: ""
  sentry_dsn: ""
  enable_metrics: true

# Integration Settings
integrations:
  jira:
    enabled: false
    url: ""
    username: ""
    api_token: ""
  servicenow:
    enabled: false
    instance: ""
    username: ""
    password: ""

# Dashboard Configuration
dashboard:
  confluence_dashboard_url: "https://confluence.charlie.com/display/SERVICE/Dashboards"
  p0_dashboard_url: "https://grafana.charlie.com/d/service-p0"
  l1_dashboard_url: "https://grafana.company.com/d/service-l1"
  services_dashboard_url: "https://grafana.company.com/d/service-overview"
  wcnp_dashboard_url: "https://grafana.company.com/d/service-wcnp"
  istio_dashboard_url: "https://grafana.company.com/d/service-istio"

# External CRQ Template Configuration
external_template:
  enabled: false
  template_url: ""
  template_type: "auto"
  cache_duration: 3600
  fallback_to_builtin: true 